# Copyright 2020 Maarten Mulders
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: SonarCloud analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v4.1.1
        with:
          path: ~/.m2/repository
          key: puml-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 17
          distribution: 'adopt'
          check-latest: true

      - name: Download Apache Maven 3.9.6
        run: |
          pushd ~
          curl -LOJ https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          tar -xzf apache-maven-3.9.6-bin.tar.gz

      - name: SonarCloud Scan
        run: ~/apache-maven-3.9.6/bin/mvn -B --no-transfer-progress -P sonarcloud -Dsonar.login=$SONAR_TOKEN verify sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
